services:
  - type: web
    name: outside-the-story
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: SERVE_STATIC
        value: "1"
